/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface MenuItem {
  'id' : bigint,
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'price' : number,
}
export interface Reservation {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'date' : string,
  'guestCount' : bigint,
  'time' : string,
  'notes' : string,
  'phone' : string,
}
export interface RestaurantInfo {
  'name' : string,
  'email' : string,
  'address' : string,
  'openingHours' : string,
  'phone' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMenuItem' : ActorMethod<[MenuItem], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createReservation' : ActorMethod<[Reservation], bigint>,
  'deleteMenuItem' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMenuItem' : ActorMethod<[bigint], [] | [MenuItem]>,
  'getMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getReservations' : ActorMethod<[], Array<Reservation>>,
  'getRestaurantInfo' : ActorMethod<[], RestaurantInfo>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerCaller' : ActorMethod<[], string>,
  'registerCaller' : ActorMethod<[], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateMenuItem' : ActorMethod<[bigint, MenuItem], undefined>,
  'updateReservationStatus' : ActorMethod<[bigint, string], undefined>,
  'updateRestaurantInfo' : ActorMethod<[RestaurantInfo], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
